// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3HM5suKUcNwgGsjiyEkbVvbtOsQVnVYw',
    appId: '1:873446906535:web:4d13dd75df3f5457571982',
    messagingSenderId: '873446906535',
    projectId: 'inturn-7f7b2',
    authDomain: 'inturn-7f7b2.firebaseapp.com',
    storageBucket: 'inturn-7f7b2.appspot.com',
    measurementId: 'G-4FYVEN6BM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA82nFbuiSV1V9cuaUbkK3C-1v6FXP1i5o',
    appId: '1:873446906535:android:07a5ec709a7e27ad571982',
    messagingSenderId: '873446906535',
    projectId: 'inturn-7f7b2',
    storageBucket: 'inturn-7f7b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2jahk4baTHPbELOAu51Dj3rGA1z7EVBA',
    appId: '1:873446906535:ios:34ae86afc0a4f082571982',
    messagingSenderId: '873446906535',
    projectId: 'inturn-7f7b2',
    storageBucket: 'inturn-7f7b2.appspot.com',
    iosBundleId: 'com.example.leap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2jahk4baTHPbELOAu51Dj3rGA1z7EVBA',
    appId: '1:873446906535:ios:faad7cbdeef405a2571982',
    messagingSenderId: '873446906535',
    projectId: 'inturn-7f7b2',
    storageBucket: 'inturn-7f7b2.appspot.com',
    iosBundleId: 'com.example.leap.RunnerTests',
  );
}
